# Generated by Django 4.0.4 on 2022-05-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thandaperu', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('city', models.TextField()),
                ('street', models.CharField(max_length=100)),
                ('premises', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('phonenumber', models.IntegerField()),
                ('adhaar', models.IntegerField()),
                ('landBefore', models.CharField(max_length=100)),
                ('landAfter', models.CharField(max_length=100)),
                ('thalukVerification', models.CharField(max_length=100)),
                ('villageVerification', models.CharField(max_length=100)),
                ('notification', models.BooleanField(default=False)),
            ],
        ),
    ]
