# Generated by Django 4.0.4 on 2022-05-27 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landConversion', '0005_thaluk_village'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='adhaar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='landAfter',
        ),
        migrations.RemoveField(
            model_name='user',
            name='landBefore',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='user',
            name='premises',
        ),
        migrations.RemoveField(
            model_name='user',
            name='street',
        ),
        migrations.RemoveField(
            model_name='user',
            name='thalukVerification',
        ),
        migrations.RemoveField(
            model_name='user',
            name='villageVerification',
        ),
    ]
