# Generated by Django 4.0.4 on 2022-05-27 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landConversion', '0006_remove_user_adhaar_remove_user_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
