# Generated by Django 4.0.4 on 2022-05-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landConversion', '0008_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField()),
                ('pincode', models.BigIntegerField()),
                ('landSize', models.BigIntegerField()),
                ('landBefore', models.CharField(max_length=100)),
                ('landAfter', models.CharField(max_length=100)),
                ('thalukVerification', models.CharField(max_length=100)),
                ('villageVerification', models.CharField(max_length=100)),
                ('notification', models.BooleanField(default=False)),
                ('thandaperu', models.BigIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='landAfter',
        ),
        migrations.RemoveField(
            model_name='user',
            name='landBefore',
        ),
        migrations.RemoveField(
            model_name='user',
            name='landSize',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='user',
            name='thalukVerification',
        ),
        migrations.RemoveField(
            model_name='user',
            name='villageVerification',
        ),
    ]
